// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeW67KQAROZ5SJ54TkdDUke5MTDeAyUwo',
    appId: '1:1053092729115:web:8f312873acc85abaa303be',
    messagingSenderId: '1053092729115',
    projectId: 'healthhubcustomer',
    authDomain: 'healthhubcustomer.firebaseapp.com',
    storageBucket: 'healthhubcustomer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtTC-hd1IABSV-n9_ZXRC1pv3ONpXMH-M',
    appId: '1:1053092729115:android:1d7c97c92556ea58a303be',
    messagingSenderId: '1053092729115',
    projectId: 'healthhubcustomer',
    storageBucket: 'healthhubcustomer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfEwCghhSAypXybkIJBIUXJ5QMfV5_sLU',
    appId: '1:1053092729115:ios:e253050941ce4fbaa303be',
    messagingSenderId: '1053092729115',
    projectId: 'healthhubcustomer',
    storageBucket: 'healthhubcustomer.appspot.com',
    iosBundleId: 'com.app.healthhubcustomer',
  );
}
